import React from "react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ minHeight: "100vh", backgroundColor: "#d1d0ca" }}>
        {children}
      </body>
    </html>
  )
}
